blog/urls.py
from django.conf.urls import include,url
from .views import PostCreate,PostDetail,PostList,PostUpdate,PostDelete,PostArchiveYear,PostArchiveMonth


urlpatterns=[
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),

    url(r'^(?P<slug>[\w\-]+)/detail/$',
        PostDetail.as_view(),
        name='blog_post_detail'),

    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),

    url(r'^(?P<slug>[\w\-]+)/update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),

    url(r'^(?P<slug>[\w\-]+)/delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),

    url(r'^(?P<year>[0-9]{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),

    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),

]

blogging/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView,RedirectView
from organizer.urls import (tag as tag_urls, department as department_urls)
from blog import urls as blog_urls
from contact import urls as contact_urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',
        RedirectView.as_view(
            pattern_name='blog_post_list',
            permanent=False)),
    #url(r'^$',TemplateView.as_view(template_name='organizer/base_organizer.html')),
    url(r'^tag/',include(tag_urls)),
    url(r'^department/',include(department_urls)),
    url(r'^blog/',include(blog_urls)),
    url(r'^contact',include(contact_urls)),

]

organizer/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=31,
                            unique=True,)
    slug = models.SlugField(max_length=31,
                            unique=True,
                            help_text='A label for url config')

    class Meta:
        ordering = ['name']


    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('organizer_tag_detail',kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('organizer_tag_update',kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer_tag_delete',kwargs={'slug':self.slug})



class Department(models.Model):
    name = models.CharField(max_length=31,
                            db_index=True)
    slug = models.SlugField(max_length=31,
                            unique=True,
                            help_text='a label for url config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag,
                                  blank=True)


    class Meta:
        ordering = ['name']
        get_latest_by = ['founded_date']


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('organizer_department_detail',kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer_department_delete',kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('organizer_department_update',kwargs={'slug':self.slug})

    def get_newslink_create_url(self):
        return reverse('department_newslink_create',kwargs={'dept_slug':self.slug})

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    department = models.ForeignKey(Department)



    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together = ('slug','department')


    def __str__(self):
        return '{}: {}'.format(self.department,
                               self.title)


    def get_absolute_url(self):
        return self.department.get_absolute_url()

    def get_delete_url(self):
        return reverse('department_newslink_delete',
                       kwargs={'department_slug':self.department.slug,'newslink_slug':self.slug})

    def get_update_url(self):
        return reverse('department_newslink_update',
                       kwargs={'department_slug':self.department.slug,'newslink_slug':self.slug})

organizer/forms.py
from django.core.exceptions import ValidationError
from django import forms
from organizer.models import Department,Tag,NewsLink

class SlugClenMixin:
    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug


class TagForm(SlugClenMixin,forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()


class DepartmentForm(SlugClenMixin,forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

class NewsLinkForm(SlugClenMixin,forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'

organizer/views.py
from django.shortcuts import render
from django.views.generic import CreateView,DetailView,ListView,DeleteView,UpdateView
from .models import Tag,Department,NewsLink
from .forms import TagForm,DepartmentForm,NewsLinkForm
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator
# Create your views here.

class TagCreate(CreateView):
    model = Tag
    form_class = TagForm

class TagDetail(DetailView):
    model = Tag

class TagList(ListView):
    paginate_by = 3
    model = Tag

class TagUpdate(UpdateView):
    model = Tag
    form_class = TagForm
    template_name_suffix = '_form_update'

class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('organizer_tag_list')


class DepartmentCreate(CreateView):
    model = Department
    form_class = DepartmentForm

class DepartmentList(ListView):
    paginate_by = 3
    model = Department


class DepartmentDetail(DetailView):
    model = Department


class DepartmentDelete(DeleteView):
    model = Department
    success_url = reverse_lazy('organizer_department_list')

class DepartmentUpdate(UpdateView):
    model = Department
    form_class = DepartmentForm
    template_name_suffix = '_form_update'


class NewsLinkCreate(CreateView):
    model = NewsLink
    form_class = NewsLinkForm


class NewsLinkDelete(DeleteView):
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'

    def get_success_url(self):
        return (self.object.department.get_absolute_url())

class NewsLinkUpdate(UpdateView):
    model = NewsLink
    form_class = NewsLinkForm
    slug_url_kwarg = 'newslink_slug'
    template_name_suffix = '_form_update'

organizer/templates/organizer/base_organizer.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <title>
        {% block title %}
            Blog
        {% endblock %}
    </title>

    <!--Blog post style -->
    <link rel="stylesheet" type="text/css" href="{% static 'organizer/blog_style.css' %}">
    <!--Form and button style -->
    <link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="nav">
          <a class="nav-link" href="{% url 'blog_post_list' %}">Blog</a>
          <a class="nav-link" href="{% url 'organizer_department_list' %}">Department</a>
          <a class="nav-link" href="{% url 'organizer_tag_list' %}">Tags</a>
          <a class="nav-link" href="#">About</a>
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </nav>
      </div>
    </div>

    <div class="blog-header">
      <div class="container">
        <div class='bog-title'>
           {% block heading %}
           {% endblock %}
        </div>
         
      </div>
    </div>








    <div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% if messages %}
               <div class="alert alert-success" role="alert">
                      {% for message in messages %}
                          <button type="button" class="close" data-dismiss="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>&times;</button>{{ message }}
                     {% endfor %}
               </div>

          {% endif %}

          {% block content %}
          {% endblock %}

           <nav class="blog-pagination">

             {% if is_paginated %}

                <div class="pagination">
                    <span class="step-links">
                       {% if page_obj.has_previous %}
                            <a  class="btn btn-outline-primary"
                                href="?page={{ page_obj.previous_page_number }}">
                              prev</a>
                       {% endif %}

                    <span class="current">
                           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

               {% if page_obj.has_next %}
                     <a class="btn btn-outline-primary"
                        href="?page={{ page_obj.next_page_number }}">
                       next</a>
               {% endif %}
                   </span>
           </div>
             {% endif %}
           </nav>
        </div><!-- /.blog-main -->

           <div class="col-sm-3 offset-sm-1 blog-sidebar">
              {% block button %}
              {% endblock %}

        </div><!-- /.blog-sidebar -->

         

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>
</html>

organizer/templates/organizer/department_confirm_delete.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
          Delete Department
{% endblock %}

 {% block heading %}
 <h2>{{department.name|title}}</h2>
 {% endblock %}

{% block content %}


      <form action="{{ department.get_delete_url }}" method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          department {{ department.name }}?
        </p>
        <a href="{{ department.get_absolute_url }}" class="button button-primary">Cancel</a>
        <button type="submit">Delete Dept</button>
      </form>


{% endblock %}

organizer/templates/organizer/department_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
         {{ startup.name }}
{% endblock %}

{% block heading %}
   <h2>{{ department.name }}</h2>
   <ul class="inline">
       <a href="{{department.get_update_url}}" class="button">Edit Dept</a>
       <a href="{{department.get_delete_url}}" class="button">Delete Dept</a>
   </ul>
{% endblock %}


{% block content %}
<article>
    <dl>
    <dt>Date Founded</dt>
      <dd>{{ department.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ department.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ department.contact }}</dd>
        <dt>Tag{{ department.tags.count|pluralize }}</dt>
        {% for tag in department.tags.all %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  {{ startup.description|linebreaks }}



      {% if department.newslink_set.all %}
         <h2>Recent News </h2>
         {% endif %}
         <a href="{{ department.get_newslink_create_url }}" class="button button-primary">Add article</a>


            <ul>
              {% for newslink in department.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">{{ newslink.title|title }}</a>
                </li>
                    <a href="{{newslink.get_update_url}}" class="button">Edit Link</a>
                    <a href="{{newslink.get_delete_url}}" class="button">Delete Link</a>

              {% endfor %}
            </ul>




</article>
{% endblock %}

{% block button %}
    {% if department.blog_posts.all %}
        <h2>Blog Post{{ department.blog_posts.all|pluralize }}</h2>
            <ul>
              {% for post in department.blog_posts.all %}
                <li>
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>

    {% endif %}
{% endblock %}

organizer/templates/organizer/department_form.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                    Department
{% endblock %}

 {% block heading %}
 <h2>Department Create</h2>
 {% endblock %}

{% block content %}

  <form action="{% url 'organizer_department_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Create Department</button>
  </form>


{% endblock %}

organizer/templates/organizer/department_form_update.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                   Department update
{% endblock %}

 {% block heading %}
 <h2>Department Update</h2>
 {% endblock %}

{% block content %}

  <form action="{{department.get_update_url}}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Update Dept</button>
  </form>


{% endblock %}

organizer/templates/organizer/department_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
          Department List
{% endblock %}


{% block heading %}
       <h2>Department List</h2>
{% endblock %}


{% block button %}
        <a href="{% url 'organizer_department_create' %}" class="button button-primary">Create New Department</a>
{% endblock %}

{% block content %}

  <ul>
    {% for department in department_list %}
      <li>
        <a href=" {{ department.get_absolute_url }}">{{ department.name|title }}</a>

          <ul class="inline">
              <a href="{{department.get_update_url}}" class="button">Edit Dept</a></li>
              <a href="{{department.get_delete_url}}" class="button">Delete Dept</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>There are currently no Department available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
          Delete Newslink
{% endblock %}

   {% block heading %}
 <h2>{{newslink.title|title}}</h2>
 {% endblock %}

{% block content %}


      <form action="{{ newslink.get_delete_url }}" method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ newslink.name }}?
        </p>
        <a href="{{ newslink.department.get_absolute_url }}" class="button button-primary">Cancel</a>
        <button type="submit">Delete Tag</button>
      </form>


{% endblock %}

organizer/templates/organizer/newslink_form.html
  {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                    Newslink
{% endblock %}

 {% block heading %}
 <h2>Newslink Create</h2>
 {% endblock %}

{% block content %}

  <form action="{{ department.get_newslink_create_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Newslink Create</button>
  </form>


{% endblock %}

organizer/templates/organizer/newslink_form_update.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                    Newslink update
{% endblock %}

 {% block heading %}
 <h2>NewsLink Update</h2>
 {% endblock %}

{% block content %}

  <form action="{{newslink.get_update_url}}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Update NewsLink</button>
  </form>


{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
          Delete Tag
{% endblock %}

{% block content %}


      <form action="{{ tag.get_delete_url }}" method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ tag.name }}?
        </p>
        <a href="{{ tag.get_absolute_url }}" class="button button-primary">Cancel</a>
        <button type="submit">Delete Tag</button>
      </form>


{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
         {{ tag.name|title }}
{% endblock %}


{% block heading %}
         <h2>{{ tag.name|title }}</h2>
             <ul class="inline">
                 <a href="{{ tag.get_update_url }}" class="button">Edit Tag</a>
                 <a href="{{ tag.get_delete_url }}" class="button">Delete Tag</a>
             </ul>

{% endblock %}

{% block button %}

{% endblock %}

{% block content %}




  {% if tag.department_set.all %}
    <section>
      <h3>Department{{ tag.department_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.department_set.count }}
        department{{ tag.department_set.count|pluralize }}.
      </p>
      <ul>
        {% for department in tag.department_set.all %}
          <li><a href="{{department.get_absolute_url}}">
            {{ department.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.department_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
{% endblock %}

organizer/templates/organizer/tag_form.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                    Tag
{% endblock %}

 {% block heading %}
 <h2>Tag Create</h2>
 {% endblock %}

{% block content %}

  <form action="{% url 'organizer_tag_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Create Tag</button>
  </form>


{% endblock %}

organizer/templates/organizer/tag_form_update.html
 {% extends parent_template|default:"organizer/base_organizer.html" %}




{% block title %}
                    Tag update
{% endblock %}

 {% block heading %}
 <h2>Tag Update</h2>
 {% endblock %}

{% block content %}

  <form action="{{tag.get_update_url}}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Update Tag</button>
  </form>


{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
          Tag List
{% endblock %}


{% block heading %}
       <h2>Tag List</h2>
{% endblock %}


{% block button %}
        <a href="{% url 'organizer_tag_create' %}" class="button button-primary">Create New Tag</a>
{% endblock %}

{% block content %}

  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a>

          <ul class="inline">
              <a href="{{ tag.get_update_url }}" class="button">Edit Tag</a></li>
              <a href="{{ tag.get_delete_url }}" class="button">Delete Tag</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}